# Generated by Django 4.2.5 on 2023-10-02 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('link', models.CharField(max_length=255)),
                ('duration', models.IntegerField()),
                ('product', models.ManyToManyField(related_name='product', to='product.product')),
            ],
        ),
    ]
