# Generated by Django 4.2.5 on 2023-10-03 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='last_view',
            field=models.DateField(auto_created=True, null=True),
        ),
    ]
