# Generated by Django 4.2.5 on 2023-10-03 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0002_lesson_last_view'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='last_view',
        ),
    ]
