# Generated by Django 4.2.5 on 2023-10-03 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_user_watch_status_remove_user_watch_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlessonprogress',
            name='last_view',
            field=models.DateField(auto_created=True, null=True),
        ),
    ]
