# Generated by Django 4.2.5 on 2023-10-02 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_user_watch_status_remove_user_watch_time_and_more'),
        ('access', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='access',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_set', to='user.user'),
        ),
    ]
